<section class="register">
    <h2>Upload</h2>
    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission.
            Please correct them as indicated below.
        </p>
    <?php endif; ?>

    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(null, array('controller' => 'upload-manager', 'action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>

    <dl class="zend_form">
        <dt><?php echo $this->formLabel($form->get('description')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('description'));
            echo $this->formElementErrors($form->get('description'));
            ?></dd>
        <dt><?php echo $this->formLabel($form->get('fileupload')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('fileupload'));
            echo $this->formElementErrors($form->get('fileupload'));
            ?></dd>
        <dd><?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?></dd>
    </dl>

    <?php echo $this->form()->closeTag(); ?>
</section>